server:
  port: 9000
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
    context-path: /eqbs
#自设计的工具库starter,enableGlobalResponse开启全局响应，enablePage开启分页配置
lms:
  global:
    enableRedis: true


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://123.249.23.88:3306/question?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: c2412902
  redis:
    host: 123.249.23.88
    port: 6379
    password: c219034
#开启swagger配置
swagger:
  open: true
  scanPackage: com.lms.question
  title: question-server
  version: 1.0.0
  description: 深度学习题库练习系统
predict-server:
  predict-url: http://localhost:5000/predict



mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl